# ASSIGNMENT

1. Create a 4x4 matrix with values ranging from 0 to 3.\
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](image/assignment2.png)

In [7]:
import numpy as np

In [8]:
x = np.zeros(16,)
x[1:14:4] = 1
x[2:15:4] = 2
x[3::4] = 3
x = x.reshape(4,4)
x

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.\
![](image/assignment.png)

In [9]:
y = np.arange(0,16).reshape(4,4)
y = np.hsplit(y,2)
y

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

3. Soal Tambahan:

Misalkan kita memiliki data array seperti berikut:

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
       
Tuliskan proses filtering untuk mendapatkan hanya elemen data yang berupa bilangan prima!


Jika dilihat dari data, output yang diinginkan: 2, 3, 5, 7, 11, 13, 17, 19, 23

In [17]:
z = np.arange(1,26).reshape(5,5)
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
def prime_num(n):
    if n == 1:
        return False
    if n == 2:
        return True
    for i in range(2,n):
        if n % i == 0:
            return False
    return True

prime = []
for line in z:
    for item in line:
        if prime_num(item):
            prime.append(item)
            
z2 = np.array(prime)
z2

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23])

In [15]:
#list comprehension
z3 = np.array([item for item in z.flatten() if prime_num(item)])
z3

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23])