## Exercise 2

1. Generate a 1-D array containing 5 random integers from 0 to 100:

In [24]:
import numpy
from numpy import random

In [25]:
numpy.__version__

'1.19.2'

In [26]:
random.randint(0,101, size=5) #101 krn exclusive

array([25, 33, 67, 60, 44])

2. Generate a 2-D array with 3 rows, each row contains 5 random integers from 0 to 100

In [27]:
random.randint(0,101, size=(3,5)) #101 krn exclusive

array([[14, 56, 81, 65, 96],
       [24, 53, 63, 43, 90],
       [51, 54, 77, 82, 56]])

3. Generate a 1-D array of 30 evenly spaced elements between 1.5 and 5.5, inclusive.

In [28]:
numpy.linspace(1.5,5.5,30)

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])